#!/bin/bash 

filename="$1"

if [ -z "$filename" ]
	then printf 'Please provide a filename'
fi

{
	vss_tag_name='VisualStudioSolution'
	printf '<%s>\n' "$vss_tag_name"
	sed --posix --regexp-extended --file 'vcsol2xml.sed' "$filename"
	printf '</%s>\n' "$vss_tag_name"
}

